#ifndef __SWITCHES_H__
#define __SWITCHES_H__

#define SWITCHES_BASE_ADDRESS 0x50000080
#define DIP_SWITCH_STATE_ID 0
#define DIP_SWITCH_PRESSED_IRQ_ID 1
#define DIP_SWITCH_RELEASE_IRQ_ID 2
#define BUTTONS_STATE_ID 3
#define BUTTONS_PRESSED_IRQ_ID 4
#define BUTTONS_RELEASE_IRQ_ID 5
#define IRQ_LATENCY_ID 6
#define CLEAR_ALL_IRQ_ID 7

#endif
